FMCGWebApp/FMCGWebApp/Controllers/SellforceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FMCGWebApp.Manager;
using FMCGWebApp.Models;
using FMCGWebApp.ViewModels;

namespace FMCGWebApp.Controllers
{
    public class SellForceController : Controller
    {
        // GET: SellForce

        private SellOrderManager _sellOrder = new SellOrderManager();
        private ShopInfoManager _shopInfo = new ShopInfoManager();
        private AccountManager _account = new AccountManager();

        public ActionResult Index()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Home", "Account");
                ;
            }

            return View();
        }

        public ActionResult SendSellOrder()
        {
            if (Session["user"] == null)
            {
                return RedirectToAction("Home", "Account");
                ;
            }

            int employeeId = (int)Session["user"];
            List<LoginInfo> userRole = _account.GetUserRole(employeeId);
            int UserTypeId = 0;
            foreach (var loginInfo in userRole)
            {
                if (loginInfo.UserTypeId == 4)
                {
                    UserTypeId = 4;
                }
            }
            if (UserTypeId == 4)
            {
                List<SellOrderInfo> sellOrders = new List<SellOrderInfo>()
                {
                    new SellOrderInfo(){Id = 0, AreaName = "Null", CategoryName = "Null", ItemName = "Null", ShopName = "Null", Quentity = 0}
                };
                ViewBag.orderLists = sellOrders;
                ViewBag.area = _shopInfo.GetAreaList();
                ViewBag.category = _sellOrder.GetAllCategory();
                //  ViewBag.item = _sellOrder.GetAllItem();

                return View();
            }
            else
            {
                return RedirectToAction("Home", "Account");
            }

        }
        [HttpPost]
        public ActionResult SendSellOrder(SellOrder sellOrder)
        {
            sellOrder.EntryDate = DateTime.Now;
            sellOrder.Status = "Ordered";
            sellOrder.EmployeeId = (int)Session["user"];

            _sellOrder.AddSellOrder(sellOrder);

            var sellOrders = _sellOrder.GetAllOrder();


            ViewBag.area = _shopInfo.GetAreaList();
            ViewBag.category = _sellOrder.GetAllCategory();
            ViewBag.orderLists = sellOrders;
            // ViewBag.item = _sellOrder.GetAllItem();
            return View();
        }

        public ActionResult SendOrder(SellOrder sellOrder)
        {

            var sendSellOrders = _sellOrder.GetAllSellOrder();

            try
            {
                foreach (var order in sendSellOrders)
                {
                    sellOrder.EntryDate = DateTime.Now;
                    sellOrder.Status = "Ordered";
                    sellOrder.EmployeeId = (int)Session["user"];
                    sellOrder.AreaId = order.AreaId;
                    sellOrder.ShopId = order.ShopId;
                    sellOrder.CategoryId = order.CategoryId;
                    sellOrder.ItemId = order.ItemId;
                    sellOrder.Quantity = order.Quantity;

                    _sellOrder.SendSellOrder(sellOrder);
                }

                _sellOrder.ClearHistory();

            }
            catch (Exception exception)
            {
                ViewBag.ShowMsg = exception.Message;
            }


            return RedirectToAction("SendSellOrder");
        }

        public JsonResult GetShopByAreaId(int deptId)
        {
            var courses = _sellOrder.GetAllShop(deptId);
            return Json(courses.ToList(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetItemByCategoryId(int deptId)
        {
            var courses = _sellOrder.GetAllItem(deptId);
            return Json(courses.ToList(), JsonRequestBehavior.AllowGet);
        }
    }
}

FMCGWebApp/FMCGWebApp/Views/SellForce/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutSellForce.cshtml";
}
<section class="wrapper">
    <div class="row">
        <div class="panel-body">
            <div class="col-md-12 w3ls-graph">

                <h3 style="text-align: center; color: green"> Wellcome To Sell Force Login </h3>
            </div>
        </div>
    </div>
    <div style="margin-bottom: 415px"></div>
</section>

FMCGWebApp/FMCGWebApp/Views/SellForce/SendSellOrder.cshtml
@using FMCGWebApp.Models
@model FMCGWebApp.Models.SellOrder

@{
    ViewBag.Title = "SendSellOrder";
    Layout = "~/Views/Shared/_LayoutSellForce.cshtml";
}

<div id="page-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <div class="fBody">
                    <h3 style="text-align: center;margin-top: 100px">Send Sell Order</h3>
                    @using (Html.BeginForm(null, null, FormMethod.Post, new { name = "sellOrderValidasion", id = "sellOrderValidasion" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="form-group">
                                <div class="col-md-12">
                                    <label id="ShowAreaId" class="control-label"></label>
                                    <select name="AreaId" id="AreaId" class="form-control">
                                        <option value="">--Select Area--</option>
                                        @foreach (var area in ViewBag.area)
                                        {
                                            <option value="@area.Id">@area.AreaName</option>
                                        }
                                    </select>
                                    @Html.ValidationMessageFor(model => model.AreaId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-12">
                                    <label id="ShowShopId" class="control-label"></label>
                                    <select name="ShopId" id="ShopId" class="form-control">
                                        <option value="">Select Shop</option>

                                    </select><label id="ShopId" style="color: red;"></label>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-12">
                                    <label id="ShowCategoryId" class="control-label"></label>
                                    <select name="CategoryId" id="CategoryId" class="form-control">
                                        <option value="">--Select Category--</option>
                                        @foreach (var category in ViewBag.category)
                                        {
                                            <option value="@category.Id">@category.CategoryName</option>
                                        }
                                    </select>
                                    @Html.ValidationMessageFor(model => model.ShopId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-12">
                                    <label id="ShowItemId" class="control-label"></label>
                                    <select name="ItemId" id="ItemId" class="form-control">
                                        <option value="">Select Item </option>

                                    </select><label id="ItemId" style="color: red;"></label>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-12">
                                    <label id="ShowQuentity"></label>
                                    <input type="text" id="Quantity" name="Quantity" class="ggg" placeholder="Enter Quantity" />
                                    @*@Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", PlaceHolder = "Please Enter Quantity" } })*@
                                    @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-4">
                                    <input type="submit" value="Send Order" class="btn btn-success btn-block" />
                                </div>
                            </div>
                            <h4> @ViewBag.ShowMsg</h4>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>


<div id="page-wrapper">
    <table id="showAllOrdered" class="table table-striped table-bordered" style="width: 100%">
        <thead>
            <tr>
                <th style="text-align: center; color: green">
                    @Html.DisplayName("Serial Number")
                </th>
                <th style="text-align: center; color: green">
                    @Html.DisplayName("Shop Name")
                </th>
                <th style="text-align: center; color: green">
                    @Html.DisplayName("Category Name")
                </th>
                <th style="text-align: center; color: green">
                    @Html.DisplayName("Item Name")
                </th>
                <th style="text-align: center; color: green">
                    @Html.DisplayName("Quantity")
                </th>
                <th style="text-align: center; color: green">
                    @Html.DisplayName("Remove")
                </th>
            </tr>
        </thead>

        <div>
            <h3 style="text-align: center;margin-top: 80px">Compare Order and Stock</h3>

        </div>
        <tbody>
            @foreach (var item in ViewBag.orderLists)
            {
                <tr>

                    <td style="text-align: center; color: black">
                        @item.Id
                    </td>
                    <td style="text-align: center; color: black">
                        @item.ShopName
                    </td>
                    <td style="text-align: center; color: black">
                        @item.CategoryName
                    </td>
                    <td style="text-align: center; color: black">
                        @item.ItemName
                    </td>
                    <td style="text-align: center; color: black">
                        @item.Quentity
                    </td>
                    <td style="text-align: center; color: black">
                        @Html.ActionLink("Remove", "", "")
                    </td>


                </tr>
            }
        </tbody>

    </table>
    <div class="form-group">
        <div class="col-md-4">
            <button class="btn btn-success btn-block"> @Html.ActionLink("Send Order", "SendOrder", "SellForce") </button>
        </div>
    </div>

</div>
<div style="margin-bottom: 350px"></div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $("#AreaId").click(function () {
                $("#ShowAreaId").text("Area Name");
            });
            $("#ShopId").click(function () {
                $("#ShowShopId").text("Shop Name");
            });
            $("#CategoryId").click(function () {
                $("#ShowCategoryId").text("Category Name");
            });
            $("#ItemId").click(function () {
                $("#ShowItemId").text("Item Name");
            });
            $("#Quantity").click(function () {
                $("#ShowQuentity").text("Quantity");
            });
        });

        $("#sellOrderValidasion").validate({
            rules: {

                AreaId: "required",
                ShopId: "required",
                CategoryId: "required",
                ItemId: "required",
                Quantity: "required",

            },
            messages: {

                AreaId: "Please Select Area Name",
                ShopId: "Please Select Shop Name",
                CategoryId: "Please Select Category Name",
                ItemId: "Please Select Item Name",
                Quantity: "Please Enter Quantity",

            }
        });

        $("#AreaId").change(function () {

            var shopId = $("#AreaId").val();
            var jsonData = { deptId: shopId };

            $("#ShopId").empty();
            $("#ShopId").append('<option value=""> Select Shop </option>');

            $.ajax({
                type: "POST",
                url: '@Url.Action("GetShopByAreaId", "SellForce")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(jsonData),
                dataType: "json",
                success: function (data) {
                    // alert("Success");
                    $.each(data, function (key, value) {
                        // alert(value.Id + " " + value.CourseCode);
                        $("#ShopId").append('<option value=' + value.Id + '>' + value.ShopName + '</option>');
                    });
                }
            });
        });

        $("#CategoryId").change(function () {

            var shopId = $("#CategoryId").val();
            var jsonData = { deptId: shopId };

            $("#ItemId").empty();
            $("#ItemId").append('<option value=""> Select Item </option>');

            $.ajax({
                type: "POST",
                url: '@Url.Action("GetItemByCategoryId", "SellForce")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(jsonData),
                dataType: "json",
                success: function (data) {
                    // alert("Success");
                    $.each(data, function (key, value) {
                        // alert(value.Id + " " + value.CourseCode);
                        $("#ItemId").append('<option value=' + value.Id + '>' + value.ItemName + '</option>');
                    });
                }
            });
        });
    </script>

}